SELECT TO_CHAR(SYSDATE,'DD-MON-YYYY') FROM dual;
SELECT TO_NUMBER('123') FROM dual;
SELECT TO_DATE('25-04-2026','DD-MM-YYYY') FROM dual;

SELECT UPPER('trilok') FROM dual;
SELECT LOWER('TRILOK') FROM dual;
SELECT INITCAP('trilok mabbu') FROM dual;
SELECT LENGTH('Trilok') FROM dual;
SELECT SUBSTR('Trilok',1,3) FROM dual;
SELECT INSTR('Trilok','lo') FROM dual;

SELECT SYSDATE FROM dual;
SELECT NEXT_DAY(SYSDATE,'MONDAY') FROM dual;
SELECT ADD_MONTHS(SYSDATE,2) FROM dual;
SELECT LAST_DAY(SYSDATE) FROM dual;